apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cf-dns-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cf-dns-sync
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cf-dns-sync-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-cf-dns-sync
subjects:
- kind: ServiceAccount
  name: k8s-cf-dns-sync
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
type: Opaque
data:
  api-key: <base64 Cloudflare API Key>
  email: <base64 Cloudflare email>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cf-dns-sync
  labels:
    app: k8s-cf-dns-sync
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-cf-dns-sync
  template:
    metadata:
      labels:
        app: k8s-cf-dns-sync
    spec:
      serviceAccountName: k8s-cf-dns-sync
      containers:
      - name: k8s-cf-dns-sync
        image: quay.io/adrianchifor/kubernetes-cloudflare-sync:master
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        env:
        - name: DNS_NAME
          value: test1.example.com,test2.example.com
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: api-key
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: email
        - name: CF_PROXY
          value: "true"
        - name: CF_TTL
          value: "1"
